package com.fordays.masssending.message._entity;



/**
 * Assignment generated by hbm2java
 */


public class _Assignment 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String name;
     protected String content;
     protected String founder;
     protected java.sql.Timestamp createTime;
     protected java.sql.Timestamp beginTime;
     protected java.sql.Timestamp finishTime;
     protected Long status;
     protected java.util.Set assignMessages = new java.util.HashSet(0);

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    


    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    


    public String getFounder() {
        return this.founder;
    }
    
    public void setFounder(String founder) {
        this.founder = founder;
    }
    


    public java.sql.Timestamp getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(java.sql.Timestamp createTime) {
        this.createTime = createTime;
    }
    


    public java.sql.Timestamp getBeginTime() {
        return this.beginTime;
    }
    
    public void setBeginTime(java.sql.Timestamp beginTime) {
        this.beginTime = beginTime;
    }
    


    public java.sql.Timestamp getFinishTime() {
        return this.finishTime;
    }
    
    public void setFinishTime(java.sql.Timestamp finishTime) {
        this.finishTime = finishTime;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public java.util.Set getAssignMessages() {
        return this.assignMessages;
    }
    
    public void setAssignMessages(java.util.Set assignMessages) {
        this.assignMessages = assignMessages;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


