package com.fordays.masssending.message._entity;



/**
 * AssignMessage generated by hbm2java
 */


public class _AssignMessage 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected java.sql.Timestamp sendedtime;
     protected Long status;
     protected String memo;
     protected com.fordays.masssending.message.Assignment assignment;
     protected com.fordays.masssending.message.MessageSection messageSection;
     protected com.fordays.masssending.user.SysUser sysUser;
     protected com.fordays.masssending.forum.Account account;
     protected java.util.Set assignMessageLogs = new java.util.HashSet(0);

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public java.sql.Timestamp getSendedtime() {
        return this.sendedtime;
    }
    
    public void setSendedtime(java.sql.Timestamp sendedtime) {
        this.sendedtime = sendedtime;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }
    


    public com.fordays.masssending.message.Assignment getAssignment() {
        return this.assignment;
    }
    
    public void setAssignment(com.fordays.masssending.message.Assignment assignment) {
        this.assignment = assignment;
    }
    


    public com.fordays.masssending.message.MessageSection getMessageSection() {
        return this.messageSection;
    }
    
    public void setMessageSection(com.fordays.masssending.message.MessageSection messageSection) {
        this.messageSection = messageSection;
    }
    


    public com.fordays.masssending.user.SysUser getSysUser() {
        return this.sysUser;
    }
    
    public void setSysUser(com.fordays.masssending.user.SysUser sysUser) {
        this.sysUser = sysUser;
    }
    


    public com.fordays.masssending.forum.Account getAccount() {
        return this.account;
    }
    
    public void setAccount(com.fordays.masssending.forum.Account account) {
        this.account = account;
    }
    


    public java.util.Set getAssignMessageLogs() {
        return this.assignMessageLogs;
    }
    
    public void setAssignMessageLogs(java.util.Set assignMessageLogs) {
        this.assignMessageLogs = assignMessageLogs;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


