package com.fordays.masssending.message._entity;



/**
 * MessageSection generated by hbm2java
 */


public class _MessageSection 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected Long status;
     protected com.fordays.masssending.forum.Section section;
     protected com.fordays.masssending.message.Message message;
     protected java.util.Set assignMessages = new java.util.HashSet(0);
     protected com.fordays.masssending.forum.Topic topic;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public com.fordays.masssending.forum.Section getSection() {
        return this.section;
    }
    
    public void setSection(com.fordays.masssending.forum.Section section) {
        this.section = section;
    }
    


    public com.fordays.masssending.message.Message getMessage() {
        return this.message;
    }
    
    public void setMessage(com.fordays.masssending.message.Message message) {
        this.message = message;
    }
    


    public java.util.Set getAssignMessages() {
        return this.assignMessages;
    }
    
    public void setAssignMessages(java.util.Set assignMessages) {
        this.assignMessages = assignMessages;
    }
    


    public com.fordays.masssending.forum.Topic getTopic() {
        return this.topic;
    }
    
    public void setTopic(com.fordays.masssending.forum.Topic topic) {
        this.topic = topic;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


