package com.fordays.masssending.forum._entity;



/**
 * Account generated by hbm2java
 */


public class _Account 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String loginName;
     protected String loginPassword;
     protected Long status;
     protected com.fordays.masssending.forum.Forum forum;
     protected java.util.Set assignMessages = new java.util.HashSet(0);

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getLoginName() {
        return this.loginName;
    }
    
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }
    


    public String getLoginPassword() {
        return this.loginPassword;
    }
    
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public com.fordays.masssending.forum.Forum getForum() {
        return this.forum;
    }
    
    public void setForum(com.fordays.masssending.forum.Forum forum) {
        this.forum = forum;
    }
    


    public java.util.Set getAssignMessages() {
        return this.assignMessages;
    }
    
    public void setAssignMessages(java.util.Set assignMessages) {
        this.assignMessages = assignMessages;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


