package com.fordays.masssending.forum._entity;



/**
 * Section generated by hbm2java
 */


public class _Section 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String name;
     protected String sectionUrl;
     protected Long status;
     protected java.util.Set topics = new java.util.HashSet(0);
     protected com.fordays.masssending.forum.Forum forum;
     protected java.util.Set messageSections = new java.util.HashSet(0);

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    


    public String getSectionUrl() {
        return this.sectionUrl;
    }
    
    public void setSectionUrl(String sectionUrl) {
        this.sectionUrl = sectionUrl;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public java.util.Set getTopics() {
        return this.topics;
    }
    
    public void setTopics(java.util.Set topics) {
        this.topics = topics;
    }
    


    public com.fordays.masssending.forum.Forum getForum() {
        return this.forum;
    }
    
    public void setForum(com.fordays.masssending.forum.Forum forum) {
        this.forum = forum;
    }
    


    public java.util.Set getMessageSections() {
        return this.messageSections;
    }
    
    public void setMessageSections(java.util.Set messageSections) {
        this.messageSections = messageSections;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


